/**
 * Branded HTML email shell + small composition primitives.
 *
 * Email-client compatibility is the constraint here: tables for layout,
 * inline styles only, no @media queries beyond a single mobile-friendly
 * stack. Tested with the Resend preview which mirrors Gmail / Outlook
 * rendering reasonably well.
 *
 * Every template is built from `renderEmailLayout()` so the wrapper
 * (header + footer + button styling) is one source of truth.
 */

const BRAND_NAME = "Coach Scope";
// Brand green — matches the existing Tailwind brand-600 hex.
const BRAND_PRIMARY = "#0f766e";
const BRAND_FG = "#ffffff";
const BG = "#f8fafc";
const CARD_BG = "#ffffff";
const TEXT = "#0f172a";
const MUTED = "#64748b";

export interface ActionLink {
  label: string;
  href: string;
  /** "primary" — solid green pill. "secondary" — outlined. */
  variant?: "primary" | "secondary";
}

export interface MetaRow {
  label: string;
  value: string;
}

export interface EmailLayoutInput {
  /** Subject + first heading. Keep concise (<60 chars). */
  title: string;
  /** Optional preheader — the snippet preview most clients show. */
  preheader?: string;
  /** Short paragraph above the meta table. */
  intro?: string;
  /** Key/value rows describing the event. Rendered as a borderless table. */
  meta?: MetaRow[];
  /** CTAs at the bottom. First action is rendered primary by default. */
  actions?: ActionLink[];
  /** Optional small text below the actions (caveats, safety reminders, etc.). */
  footnote?: string;
}

function escape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderButton(action: ActionLink, isPrimary: boolean): string {
  const bg = isPrimary ? BRAND_PRIMARY : "#ffffff";
  const fg = isPrimary ? BRAND_FG : BRAND_PRIMARY;
  const border = isPrimary ? BRAND_PRIMARY : "#cbd5e1";
  return `
    <a href="${escape(action.href)}"
       style="display:inline-block;padding:12px 20px;margin:0 6px 8px 0;
              background:${bg};color:${fg};text-decoration:none;
              font-weight:600;font-size:14px;border-radius:9999px;
              border:1px solid ${border};line-height:1;">
      ${escape(action.label)}
    </a>`;
}

function renderMeta(rows: MetaRow[]): string {
  return `
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%"
           style="border-collapse:collapse;margin:16px 0;">
      ${rows
        .map(
          (r) => `
        <tr>
          <td style="padding:6px 0;color:${MUTED};font-size:13px;width:120px;
                     vertical-align:top;">${escape(r.label)}</td>
          <td style="padding:6px 0;color:${TEXT};font-size:14px;
                     word-break:break-word;">${escape(r.value)}</td>
        </tr>`
        )
        .join("")}
    </table>`;
}

/**
 * Compose a complete branded HTML email. Returns a single string ready
 * to hand to the email provider. The matching plain-text fallback is
 * generated by `renderEmailText()` below — call both when you can.
 */
export function renderEmailLayout(input: EmailLayoutInput): string {
  const preheader = input.preheader
    ? `<div style="display:none;max-height:0;overflow:hidden;opacity:0;">${escape(
        input.preheader
      )}</div>`
    : "";

  const intro = input.intro
    ? `<p style="margin:0 0 8px 0;color:${TEXT};font-size:15px;line-height:1.5;">
         ${escape(input.intro)}
       </p>`
    : "";

  const meta = input.meta && input.meta.length > 0 ? renderMeta(input.meta) : "";

  const actions =
    input.actions && input.actions.length > 0
      ? `<div style="margin:16px 0 0 0;">${input.actions
          .map((a, i) =>
            renderButton(a, a.variant ? a.variant === "primary" : i === 0)
          )
          .join("")}</div>`
      : "";

  const footnote = input.footnote
    ? `<p style="margin:24px 0 0 0;color:${MUTED};font-size:12px;line-height:1.5;">
         ${escape(input.footnote)}
       </p>`
    : "";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>${escape(input.title)}</title>
</head>
<body style="margin:0;padding:0;background:${BG};font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:${TEXT};">
${preheader}
<table role="presentation" width="100%" cellpadding="0" cellspacing="0"
       style="background:${BG};padding:24px 12px;">
  <tr>
    <td align="center">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
             style="max-width:560px;background:${CARD_BG};border-radius:12px;
                    border:1px solid #e2e8f0;overflow:hidden;">
        <tr>
          <td style="padding:18px 24px;background:${BRAND_PRIMARY};color:${BRAND_FG};
                     font-size:13px;font-weight:600;letter-spacing:0.04em;
                     text-transform:uppercase;">
            ${escape(BRAND_NAME)} · Admin alert
          </td>
        </tr>
        <tr>
          <td style="padding:24px;">
            <h1 style="margin:0 0 12px 0;font-size:20px;line-height:1.3;color:${TEXT};">
              ${escape(input.title)}
            </h1>
            ${intro}
            ${meta}
            ${actions}
            ${footnote}
          </td>
        </tr>
        <tr>
          <td style="padding:14px 24px;background:#f1f5f9;color:${MUTED};
                     font-size:11px;line-height:1.5;">
            You're receiving this because you're an admin on ${escape(BRAND_NAME)}.
            Detailed evidence (proof URLs, IDs, etc.) lives only inside the
            admin portal — never in this email.
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>`;
}

/**
 * Plain-text fallback for the same layout. Resend derives one automatically
 * but supplying our own keeps the formatting predictable across clients.
 */
export function renderEmailText(input: EmailLayoutInput): string {
  const lines: string[] = [];
  lines.push(`${BRAND_NAME} · Admin alert`);
  lines.push("");
  lines.push(input.title);
  if (input.intro) {
    lines.push("");
    lines.push(input.intro);
  }
  if (input.meta && input.meta.length > 0) {
    lines.push("");
    for (const r of input.meta) {
      lines.push(`${r.label}: ${r.value}`);
    }
  }
  if (input.actions && input.actions.length > 0) {
    lines.push("");
    for (const a of input.actions) {
      lines.push(`${a.label}: ${a.href}`);
    }
  }
  if (input.footnote) {
    lines.push("");
    lines.push(input.footnote);
  }
  lines.push("");
  lines.push(
    "Sensitive evidence is intentionally omitted from this email. View details inside the admin portal."
  );
  return lines.join("\n");
}

/**
 * Resolve the public base URL used in CTA links. Order:
 *   1. NEXT_PUBLIC_APP_URL (preferred, deploy-stable)
 *   2. NEXTAUTH_URL        (already required for the auth layer)
 *   3. http://localhost:3000 (dev fallback)
 */
export function publicBaseUrl(): string {
  return (
    process.env.NEXT_PUBLIC_APP_URL ||
    process.env.NEXTAUTH_URL ||
    "http://localhost:3000"
  ).replace(/\/+$/, "");
}
