/**
 * scripts/batch-missing-dorms.ts
 *
 * Splits the dorm coverage worksheet
 *   data/exports/missing-dorms.csv
 * (produced by scripts/export-missing-dorms.ts) into batched files of
 * BATCH_SIZE universities each, ready to drop into a Claude / research
 * session for one prompt → one dorm-import CSV per batch.
 *
 * Output:
 *   data/exports/dorm-batches/dorm-batch-001.csv
 *   data/exports/dorm-batches/dorm-batch-002.csv
 *   ...
 *   data/exports/dorm-batches/README.md
 *
 * Every batch CSV preserves the original column header
 * (universityName,city,state,websiteUrl,housingUrl,dormCount) so the file
 * round-trips with the rest of the coverage workflow.
 *
 * The README is regenerated from scratch every run and lists each batch
 * with its university count — so a stale README never disagrees with the
 * batch files sitting next to it.
 *
 * Idempotent: safe to re-run. Existing batch files are overwritten with
 * the current contents of missing-dorms.csv. Old batches that no longer
 * exist (because coverage improved + the input shrunk) are removed so the
 * folder reflects the current backlog only.
 *
 * Usage:
 *   npm run dorms:batch
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from "fs";
import { join } from "path";
import Papa from "papaparse";

// 35 universities per batch — sized so one batch fits comfortably in a
// single Claude research turn (URL fetches + summarization headroom).
// If a batch is taking too long in practice, drop this number; the script
// re-batches deterministically from the same input.
const BATCH_SIZE = 35;

const INPUT_PATH = join("data", "exports", "missing-dorms.csv");
const OUT_DIR = join("data", "exports", "dorm-batches");

// Single source of truth for the worksheet column shape. Mirrors the
// header emitted by scripts/export-missing-dorms.ts. We don't infer from
// the input — explicit columns guarantee every batch file has the same
// header even if the input was reordered manually.
const COLUMNS = [
  "universityName",
  "city",
  "state",
  "websiteUrl",
  "housingUrl",
  "dormCount",
] as const;
type WorksheetRow = Record<(typeof COLUMNS)[number], string>;

function pad(n: number, width = 3): string {
  return String(n).padStart(width, "0");
}

/**
 * Minimal CSV cell escape, RFC 4180 compatible. Matches the helper used
 * in export-missing-dorms.ts so a round-trip diff is character-identical.
 */
function csvCell(v: string | null | undefined): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  if (s === "") return "";
  if (/[",\n\r]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function serializeBatch(rows: WorksheetRow[]): string {
  const header = COLUMNS.join(",");
  const body = rows
    .map((r) => COLUMNS.map((c) => csvCell(r[c])).join(","))
    .join("\n");
  return rows.length === 0 ? header + "\n" : `${header}\n${body}\n`;
}

/**
 * Remove dorm-batch-*.csv files that don't belong to the current run, so
 * a smaller backlog doesn't leave orphaned old batch numbers behind.
 * Touching only the dorm-batch-*.csv pattern avoids nuking the README or
 * anything else a researcher dropped in this folder.
 */
function pruneStaleBatches(keepCount: number) {
  if (!existsSync(OUT_DIR)) return;
  const entries = readdirSync(OUT_DIR);
  for (const f of entries) {
    const match = /^dorm-batch-(\d+)\.csv$/i.exec(f);
    if (!match) continue;
    const n = Number(match[1]);
    if (Number.isFinite(n) && n > keepCount) {
      unlinkSync(join(OUT_DIR, f));
    }
  }
}

function buildReadme(batches: WorksheetRow[][]): string {
  const totalUniversities = batches.reduce((s, b) => s + b.length, 0);
  const lines: string[] = [];
  lines.push("# Dorm research batches");
  lines.push("");
  lines.push(
    `Generated by \`scripts/batch-missing-dorms.ts\` from \`data/exports/missing-dorms.csv\`.`
  );
  lines.push(
    `Re-run \`npm run dorms:batch\` after a fresh \`npm run dorms:missing\` to refresh.`
  );
  lines.push("");
  lines.push(`- **Batches:** ${batches.length}`);
  lines.push(`- **Universities per batch (max):** ${BATCH_SIZE}`);
  lines.push(`- **Universities total in backlog:** ${totalUniversities}`);
  lines.push("");
  lines.push("## Research task");
  lines.push("");
  lines.push(
    "For each row in a batch CSV, open the university's `housingUrl` (or"
  );
  lines.push(
    "find one starting from `websiteUrl`) and pull the residence halls list"
  );
  lines.push(
    "from the official **Housing / Residence Life** page. Produce a single"
  );
  lines.push(
    "dorm-import CSV that contains every dorm discovered across the batch."
  );
  lines.push("");
  lines.push("**Hard rules:**");
  lines.push("");
  lines.push(
    "- Use ONLY official university housing / residence life pages."
  );
  lines.push(
    "- NEVER invent dorm names. If a university's housing page doesn't list"
  );
  lines.push(
    "  named residence halls, leave that university out — that's fine; the"
  );
  lines.push(
    "  worksheet will surface it again on the next coverage run."
  );
  lines.push(
    "- Don't copy from third-party rankings, niche.com, dorm-reviews sites,"
  );
  lines.push("  or marketing pages. Official only.");
  lines.push(
    "- Leave optional fields blank if you can't verify them — never guess."
  );
  lines.push("");
  lines.push("## Dorm import CSV format");
  lines.push("");
  lines.push("Header (paste verbatim as the first line of your output file):");
  lines.push("");
  lines.push("```");
  lines.push(
    "name,slug,universityName,city,state,roomType,bathroomType,yearBuilt,capacity,officialPageUrl,description,imageUrl,sourceUrl,sourceName,seasonYear,lastVerifiedAt"
  );
  lines.push("```");
  lines.push("");
  lines.push(
    "Required columns: `name`, `universityName`. Everything else is optional."
  );
  lines.push("");
  lines.push("- `roomType` ∈ {Single, Double, Suite, Apartment}");
  lines.push("- `bathroomType` ∈ {Private, Shared, Communal}");
  lines.push(
    "- `officialPageUrl` — the per-dorm housing page when one exists"
  );
  lines.push(
    "- `sourceUrl` + `sourceName` — provenance (e.g. the housing index URL"
  );
  lines.push('  + "Stanford Residential & Dining Enterprises")');
  lines.push(
    "- `seasonYear` defaults to `2025-2026` if blank; `lastVerifiedAt`"
  );
  lines.push("  defaults to now on insert and is preserved on update.");
  lines.push("");
  lines.push("## Import the result");
  lines.push("");
  lines.push("Once the dorm CSV is built, upload via the admin UI:");
  lines.push("");
  lines.push("- `/admin/import` → select type **dorms** → upload the CSV.");
  lines.push("");
  lines.push("Or from the CLI:");
  lines.push("");
  lines.push("```bash");
  lines.push("npm run db:import -- dorms path/to/your-dorm-batch-NNN.csv");
  lines.push("```");
  lines.push("");
  lines.push(
    "The importer is idempotent — rows are deduped per `(universityId, slug)`"
  );
  lines.push(
    "and per `(universityId, normalizedName)`. Re-uploading the same CSV"
  );
  lines.push("never duplicates and never deletes existing dorms.");
  lines.push("");
  lines.push("After importing a batch, run `npm run dorms:missing` to see");
  lines.push("the coverage stats update.");
  lines.push("");
  lines.push("## Batches");
  lines.push("");
  if (batches.length === 0) {
    lines.push("_No universities currently need dorm research. Nice._");
  } else {
    lines.push("| # | File | Universities |");
    lines.push("| --- | --- | --- |");
    batches.forEach((b, i) => {
      const n = pad(i + 1);
      lines.push(`| ${i + 1} | \`dorm-batch-${n}.csv\` | ${b.length} |`);
    });
  }
  lines.push("");
  return lines.join("\n");
}

function main() {
  if (!existsSync(INPUT_PATH)) {
    // eslint-disable-next-line no-console
    console.error(
      `[batch-missing-dorms] input not found: ${INPUT_PATH}\n` +
        `Run \`npm run dorms:missing\` first to generate the worksheet.`
    );
    process.exit(1);
  }

  const raw = readFileSync(INPUT_PATH, "utf-8");
  const parsed = Papa.parse<WorksheetRow>(raw, {
    header: true,
    skipEmptyLines: true,
    transformHeader: (h) => h.trim(),
    transform: (v) => (typeof v === "string" ? v.trim() : v),
  });
  if (parsed.errors.length > 0) {
    const first = parsed.errors[0];
    // eslint-disable-next-line no-console
    console.error(
      `[batch-missing-dorms] CSV parse error on row ${first.row ?? "?"}: ${first.message}`
    );
    process.exit(1);
  }

  // Defensive: drop rows that don't have a universityName so we never
  // ship a batch with an unusable blank entry. Real input from
  // export-missing-dorms.ts won't trip this; manual edits might.
  const rows = parsed.data.filter((r) => (r.universityName ?? "").trim() !== "");

  const batches: WorksheetRow[][] = [];
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    batches.push(rows.slice(i, i + BATCH_SIZE));
  }

  mkdirSync(OUT_DIR, { recursive: true });
  pruneStaleBatches(batches.length);

  for (let i = 0; i < batches.length; i++) {
    const filename = `dorm-batch-${pad(i + 1)}.csv`;
    writeFileSync(join(OUT_DIR, filename), serializeBatch(batches[i]), "utf-8");
  }

  writeFileSync(join(OUT_DIR, "README.md"), buildReadme(batches), "utf-8");

  // eslint-disable-next-line no-console
  console.log(
    `[batch-missing-dorms] wrote ${batches.length} batch file${
      batches.length === 1 ? "" : "s"
    } (${rows.length} universities, ${BATCH_SIZE}/batch) to ${OUT_DIR}/`
  );
  if (batches.length > 0) {
    console.log(
      `[batch-missing-dorms] first batch: dorm-batch-${pad(1)}.csv (${batches[0].length} rows)`
    );
    console.log(
      `[batch-missing-dorms] last  batch: dorm-batch-${pad(batches.length)}.csv (${batches.at(-1)!.length} rows)`
    );
  }
  console.log(`[batch-missing-dorms] regenerated ${OUT_DIR}/README.md`);
}

try {
  main();
} catch (err) {
  // eslint-disable-next-line no-console
  console.error("[batch-missing-dorms] fatal:", err);
  process.exit(1);
}
